### ISSUE TITLE
Redo Our team section

### ISSUE THREAD

**Issue by Descent098** [Schulich-Ignite/website#212]
## Goals

- More visibility and transparrency into team
- More networking possibilities (Linkedin links, other social media)
- Being able to recognize people that don't come up as VP's

## TODO

- [ ] Integrate Junior VP's into page
- [ ] Redesign Web team section
- [ ] Any other improvements

**Comment by Descent098** [comment]
Go from 4 column, to 3 column to 2 column

**Comment by Descent098** [comment]
- [ ] round images
- [ ] Hide description until click
