### ISSUE TITLE
create showcase section

### ISSUE THREAD

**Issue by Descent098** [Schulich-Ignite/website#215]
A place for mentors and mentee's to showcase projects

## TODO

- [ ] Convert Blog nav link to media nav link
- [ ] Make tabular nav with options
![Image](https://user-images.githubusercontent.com/22761705/216226676-c02f50cd-6cb1-4a80-b350-7f31f0718ff8.png)
  - [ ] Blog tab
  - [ ] Showcase tab
- [ ] Finalize fields
- [ ] Start creating content section
- [ ] Start creating stylesheets

## Fields

- [ ] Source code link
- [ ] Demo (static web projects)
- [ ] Content/writeup section
- [ ] Author taxonomy

**Comment by Descent098** [comment]
Horizontal scroll, can use lightbox when clicking on preview
